# Generated by Django 2.2.5 on 2022-06-24 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220624_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default=None, max_length=20, null=True, verbose_name='course_name')),
            ],
            options={
                'db_table': 'tb_label',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default=None, max_length=100, null=True, verbose_name='title')),
                ('content', models.CharField(default=None, max_length=1000, null=True, verbose_name='content')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='datetime')),
                ('labels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.Course')),
            ],
            options={
                'db_table': 'tb_question',
                'ordering': ['-createtime'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, max_length=1000, null=True, verbose_name='content')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.Post', verbose_name='postID')),
            ],
            options={
                'db_table': 'qa_reply',
            },
        ),
    ]
